### ISSUE TITLE
calibreの実行？でCIが失敗する

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text#964]
https://github.com/scala-text/scala_text/runs/7280334945

```
Error [EbookError]: Error during ebook generation: /home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)
/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)
/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)
    at createError (/home/runner/work/scala_text/scala_text/node_modules/error/typed.js:31:22)
    at Object.createError [as EbookError] (/home/runner/work/scala_text/scala_text/node_modules/error/wrapped.js:88:19)
    at /home/runner/work/scala_text/scala_text/node_modules/honkit/lib/output/ebook/onFinish.js:70:35
From previous event:
    at Command.<anonymous> (/home/runner/work/scala_text/scala_text/node_modules/honkit/lib/bin.js:35:22)
    at Command.listener [as _actionHandler] (/home/runner/work/scala_text/scala_text/node_modules/honkit/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/home/runner/work/scala_text/scala_text/node_modules/honkit/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/home/runner/work/scala_text/scala_text/node_modules/honkit/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/home/runner/work/scala_text/scala_text/node_modules/honkit/node_modules/commander/index.js:882:12)
    at Command.parse (/home/runner/work/scala_text/scala_text/node_modules/honkit/node_modules/commander/index.js:717:10)
    at /home/runner/work/scala_text/scala_text/node_modules/honkit/lib/bin.js:43:17
    at new Promise (<anonymous>) {
  type: 'ebook',
  message: "Error during ebook generation: /home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    '\n',
  stdout: '',
  causeMessage: "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n",
  origMessage: "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n" +
    "/home/runner/calibre-bin/calibre/bin/ebook-convert: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/calibre-bin/calibre/lib/libpython3.10.so.1.0)\n",
  code: 1,
  fullType: 'ebook~!~error.wrapped-unknown'
}
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:30)
```

**Comment by hiroshi-cl** [comment]
Ubuntu18.04はglibc-2.27のようなので雑に20とかにしてみると解決しないだろうか 🤔

**Comment by xuwei-k** [comment]
ほほー。
昔何かが動かなかったから(うろ覚え)、雑に古いubuntuでごまかしてるけど、そこもいずれにせよupdateしないとなぁ

**Comment by xuwei-k** [comment]
- https://github.com/scala-text/scala_text/commit/ce71646d63b835c8c2a3f3a3789244148b83ced9

雑に試す

**Comment by xuwei-k** [comment]
```
Run sudo apt-get install gcc-4.8
Reading package lists...
Building dependency tree...
Reading state information...
Package gcc-4.[8](https://github.com/scala-text/scala_text/runs/7319322320?check_suite_focus=true#step:7:9) is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'gcc-4.8' has no installation candidate
Error: Process completed with exit code [10](https://github.com/scala-text/scala_text/runs/7319322320?check_suite_focus=true#step:7:11)0.
```

はい、ubuntu-latest失敗〜〜〜

**Comment by hiroshi-cl** [comment]
😇
gcc-4.8も相当古いですけどね
9系でいけるだろうか 🤔

**Comment by xuwei-k** [comment]
gccは、そもそも色々整理したら明示的なインストール必要ない、とかあり得る
(直接インストールではなく、関連したもの全部いい感じにインストールするやつあるかも？など)

**Comment by y-yu** [comment]
gcc4.8は古すぎる…… 😇
